### ISSUE TITLE
Large Output dimension

### ISSUE THREAD

**Issue by bjschoenfeld** [rlaboulaye/attention_mechanism#1]
The target language for translation is going to have a huge output dimension. This will cause there to be a lot of weights. Is there another solution? There are probably some other language embeddings we could consider, but then mapping from predicted embedding back to the original word would not be a trivial task.

**Comment by bjschoenfeld** [comment]
Did we want to use the most common k words? With k ~= 10,000's?

**Comment by rlaboulaye** [comment]
Yeah, that's a problem that I looked into for my other project. All text generating examples I have seen simply use a large output dimension (I've seen 5,000 to 10,000 for generation and sometimes up to 40,000 for translation). I did implement an embedding to embedding network, which allowed me to use an output dimension that was only the dimension of the embedding (300). However, the issue with that approach was that you then had to translate from a point in embedding space to a word. This has two issues. First, you have to find the word through a non-deterministic process in order to do so in a reasonable amount of time (I used locality sensitive hashing). Second, this assumes that all dimensions of the embedding space are equally relevant to the word prediction, which is likely not true. This might lead to generating "scary" instead of "monster" because they are similar along a certain dimension, even though the partial sentence called for a noun next.

**Comment by rlaboulaye** [comment]
Starting with a k of 5,000 or 10,000 would be fine.
